### PR TITLE
Tests: Switched from generateUniqueId skin script to utils method.

### PR DESCRIPTION
**Pull request by reinhardt**
generateUniqueId.py will be removed soon.
See https://github.com/plone/Products.CMFPlone/issues/1801

### CODE REVIEW

**Comment by erral** [comment]
I think LinguaPlone is Plone 4 only (moreover, it's only Archetypes), so I think that the change won't have any effect on LinguaPlone, right?

**Comment by reinhardt** [comment]
> I think LinguaPlone is Plone 4 only

Ah, I didn't realise that. Feel free to close if that's the case.

**Comment by erral** [comment]
@mauritsvanrees comments?

**Comment by mauritsvanrees** [comment]
@erral is right.
For multilingual sites on Plone 5 you should use plone.app.multilingual.
I guess theoretically you could get LinguaPlone to work on Plone 5, but there should be no need.

**Pull request closed without merging**
