### PR TITLE
Added tests for sitemap

### PR DESCRIPTION
**Pull request by djowett**
This is to help make sure we don't break anything in LinguaPlone with changes in https://github.com/plone/plone.app.layout/pull/92 

cc @Rudd-O @erral @tisto

### CODE REVIEW

**Comment by djowett** [comment]
Please don't merge even if tests pass - I need to also test against checkouts of other products (p.a.layout etc)

**Comment by Rudd-O** [comment]
Yay!

**Comment by djowett** [comment]
This PR just adds tests for multilingual sitemaps, will implementing https://github.com/plone/plone.app.layout/pull/92 and related changes.  

_They could still be useful for checking that sitemaps aren't broken for LinguaPlone users by future changes elsewhere in Plone, but I would like someone who actually uses LinguaPlone (I don't) to review and merge them.  Once reviewed, they could also be rebased - I've held off on rebasing now because I want to show  the test results to anyone reviewing - contact me if rebasing is difficult._

Jenkins tests are currently failing at 
http://jenkins.plone.org/job/pull-request-4.3/490/testReport/Products.CMFPlone.tests.testSecurity/TestAttackVectorsFunctional/test_widget_traversal_2/ but that looks unrelated to the change.  They did pass earlier for 613eb26 (if you can see that).  I believe these will pass once whatever broke the test in coredev is fixed.

**Comment by erral** [comment]
I have tested this branch in a Plone 4.3.10 with Archetypes and plone.app.layout 2.3.16, and it works as expected:

- mysite.com/es/sitemap.xml.gz -> shows content only in 'es' language
- mysite.com/eu/sitemap.xml.gz -> shows content only in 'eu' language
- mysite.com/sitemap.xml.gz -> shows content in both languages

So :+1: on my side.

**Comment by djowett** [comment]
Thanks @erral.  Looks like the failing test will be fixed by https://github.com/plone/Products.CMFPlone/commit/d6274cca1b5f15b982f3711288f71757a02a3f77

Any other comments? or anyone up for merging as is?

**Comment by djowett** [comment]
This is now rebased, and tests are green.

**Pull request merged**
